package nz.ac.canterbury.seng302.portfolio.controller;

import io.grpc.StatusRuntimeException;
import nz.ac.canterbury.seng302.portfolio.authentication.CookieUtil;
import nz.ac.canterbury.seng302.portfolio.service.AuthenticateClientService;
import nz.ac.canterbury.seng302.shared.enums.Roles;
import nz.ac.canterbury.seng302.shared.identityprovider.AuthState;
import nz.ac.canterbury.seng302.shared.identityprovider.AuthenticateResponse;
import nz.ac.canterbury.seng302.shared.projectDAL.Datastore;
import nz.ac.canterbury.seng302.shared.projectDAL.model.User;

import nz.ac.canterbury.seng302.shared.projectDAL.readWrite.UserDAL;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.util.MultiValueMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.ArrayList;
import java.util.Arrays;

@Controller
public class SignUpController {

    @Autowired
    private AuthenticateClientService authenticateClientService;

    /**
     * @param request HTTP request sent to this endpoint
     * @param response HTTP response that will be returned by this endpoint
     * @param model Parameters sent to thymeleaf template to be rendered into HTML
     * @return Message generated by IdP about authenticate attempt
     */
    @GetMapping("/signUp")
    public String signUp(
            HttpServletRequest request,
            HttpServletResponse response,
            Model model
    ) {
        return "signUp";
    }

    @PostMapping("/createUser")
    public String createUser(
            HttpServletResponse response,
            @RequestParam String username,
            @RequestParam String firstName,
            @RequestParam String lastName,
            @RequestParam String nickname,
            @RequestParam String bio,
            @RequestParam String pronouns,
            @RequestParam String email,
            @RequestParam String password,
            Model model
    ) {
        System.out.println(username);
        Datastore db = new Datastore();
        if (UserDAL.addUser(db, username, firstName, lastName, nickname, bio, pronouns, email, password, "salt", new ArrayList<>(Arrays.asList(Roles.STUDENT)))) {
            User user = UserDAL.getUserByUsername(db,username);
            return "redirect:/login";
        }
        System.out.println("Redirecting");
        return "/signUp";
    }

}
