MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (1, 'Teacher for 4th year Civil Engineering project','2022-07-15 21:45:57.287000000','kennyR@yahoo.com','Kenny','Rodgers','','F76xhPVPwyAq50ITK3uioDrnSEhAsNtuMFnNMHuJYuk=',null,'','PP8rnwPCE1BmJJm4gjRQog==','Kenny');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (2,'','2022-07-15 21:51:39.227000000','furretfive@aol.com','Neil','Goodman','','+VdC80p2/3criIC8HDS6wrPavdZizLOUTJpuRF4gLZA=','UserProfile65.jpeg','He Him','n2wCS3cP9e4jrz7DNsnS6A==','FurretFive');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (3,'','2022-07-15 22:20:27.868000000','tutor@canterbury.ac.nz','Modo','Walker','','5DvNglYsbLJZIQKi36WXyLuuGX7FSUSXP8TQ1N/ZBqs=',null,'She Her','oHscOzQfdDcUPxr4Qvdqfw==','HeadTutor');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (4,'','2022-07-15 22:40:43.1000000','kyo@gmail.com','Kirsty','Yo','','0BxSImk0aNz7adQNhIdjIBDrozBPJYBxrSBcQJGJB18=',null,'','TxAXyvuoNKW1gbdda2/UyA==','LENSAdmin');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (5,'','2022-07-15 23:01:55.951000000','CharlesK@xtra.co.nz','Charlie','Kent','CK','hUf7/y8+P/KmxNwpjgPM5KGJ4GVYpDEUha7ObNPJV1k=',null,'','DqxDZhSZJkKFXKSBlmeNHA==','Squrrril');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (6,'','2022-07-16 09:50:14.298000000','Maarrk@gmail.com','Mark','Hill','','gTAYPSdxUVOhAW067lavE6g1ZDZlnR1F36V4959COqA=',null,'','tuxpzX+DQ7rZmbZr2j+5eA==','Maarrk');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (7,'I decided at a young age that I was going to be the best at using Blender. If you need anything 3d modeled, I''m your gal.','2022-07-16 10:11:15.893000000','mchase@aol.com','Mary','Chase','','KHS7nD/hOymPmaa8AfpuSQTayaay9MHGD5P0Hld8JgY=',null,'She Them','KS5qmjHGvfoGhsu3LLJZIw==','Blender');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (8,'','2022-07-20 09:15:46.746000000','MattyB@gmail.com','Matt','Bacon','','D6F7GdQJjkJvtB4c9FOJ3PVjc9Dy9pA3Z+xWWoYRbkc=',null,'','61mVQt4ygCcNl+pq4togvQ==','MattyBacon');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (9,'','2022-07-20 09:17:59.44000000','bigIron@aol.com','Marty','Robbins','','lEyDpUKGT4ZrFvFOWASZjeAtcxhuqIorn91sXS+vfVo=',null,'','DFXkJsxPizi3OSebElw19Q==','Ranger');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (10,'','2022-07-20 09:19:23.654000000','AllyB@gmail.com','Alex','Baily','','q05JSnI2LYA4oaf8JNEqlP58mDfb23rsofAT9plE70Y=',null,'She/Her','r6htHAMQbYzfd4Y9UWVkoQ==','Alex');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (11,'','2022-07-20 09:21:12.425000000','JakeB@gmail.com','Jake','Bradly','','ZqRVYiKbfex7qSrtfRq0fTrpZm2fjQQvytsdKsy7pQU=',null,'','NnY4nlePC+4/ZLkVq7l5ww==','MadJake');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (12,'','2022-07-20 09:22:14.687000000','crows@gmail.com','Stanley','Parable','Crow','Bzu61v8zXWOFXqJ3TZzuG1oSJm33zvq17NH0hwrhxus=',null,'','y+tGNoX6/CyPVIhTEys7Ag==','Stanley');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (13,'','2022-07-20 09:23:03.264000000','Sebby@gmail.com','Sebastian','Finnagin','Sebby','pVmUUlZHwZgm1Nn+xuD5pcy3Gjjnu66ryMsabjcD3i0=',null,'','afUdlvRUgkOatsGzvFWyQw==','Sebastian');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (14,'','2022-07-20 09:24:01.993000000','LSandy@gmail.com','Lewis','Sandy','','Nk/aaXsbWFQBC8sl9q2zVWanQhRqcmNgSnyIJcWnALI=',null,'','L9SbstucqvgH8Mc5QD9jqg==','Lewis');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (15,'','2022-07-20 09:25:20.381000000','Jeb@aol.com','Jebediah','Kerman','Jeb','mm7QDvDQIW/RrFHDkwFUKSdJQv079biXGqXvKc29hpQ=',null,'','N1MC0+hO4Z3puJXZIpCvqw==','Jeb');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (16,'','2022-07-20 09:26:01.24000000','cookie@jackbox.com','Cookie','Matterson','','K9NKzEp1Ko5lVvtZ6w6PbzRZmQTUbcibdUryG60Qvg8=',null,'','SU9mgtGyoVMG5ZLWOblndg==','Cookie');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (17,'','2022-07-20 09:27:25.691000000','Imogen@gmail.com','Imogen','Frank','','D8PnkQ5+v7GUg7a2R+1cUlYPsWBstTPZ4RxFEx/1Bhk=',null,'','5mTRlSoXQF4ASDYHQ1QsIQ==','Impasta');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (18,'','2022-07-20 09:28:12.64000000','JCeasar@hotmail.com','Julie','Ceasar','','anUKKOi2kZvfZexy5VhJh34OR6Sd2S/qD1gGTxAOA3c=',null,'','cWvDfP+JGaRjY/VU2uFbWw==','JCeasar');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (19,'','2022-07-20 09:29:23.968000000','cetusMain@gmail.com','Rachel','Stenson','','INglF9zZvOBi6+Oc3QOjeu3M8m1nGOk7Vkyu7MzCmMQ=',null,'She/they','8aNga7rfWK8YE8bszRG7nA==','Cetus');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (20,'','2022-07-20 09:30:34.340000000','zhirov@gmail.com','Zhirov','Plort','','0L1rv2UxdGHym5Pip4f5xJkeJOJeoy3xXuroBrslYOI=',null,'They/Them','M1+01lSJKx8q2CUuwmhinQ==','SGEMP');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (21,'','2022-07-20 09:32:09.512000000','RichardLord@gmail.com','Richard','Lord','','ANQNf0Y5ZA1rgpCZtswbr8UlWUsMA1kYmpXKgftZTNg=',null,'He/Him','RG1pd76hFl8su0Q3ek0Egw==','Wheatley');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (22,'','2022-07-20 09:33:07.723000000','MaeB@gmail.com','Mae','Borowski','','KP5PrtzKbMS4/vDlNEWNA2SzOY8TTxPScWX9HuWM4x0=',null,'','wj9FxPc0sFlJcOkgovf8fg==','MaeB');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (23,'','2022-07-20 09:42:05.749000000','CStorm@gmail.com','Cristian','Storm','','sIWElUw5TpRHEQW7BeR3o8BRCa5sQmmjeijEVZvXC8I=',null,'They/Her','LtFdir9RCbaMf0o7mNeeJQ==','Haggstrom');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (24,'','2022-07-20 09:42:55.5000000','Rozan@gmail.com','Rosan','Wigram','','8onxQOD64OSWBrdJlp1nnhgZ6OkXuh66k4TDX12NlVE=',null,'','HW9gQAv9cQq3v99jAiaKpw==','Rozan');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (25,'','2022-07-20 09:43:44.309000000','LBooker@aol.com','Liam','Booker','','0ouQtBikBkRxFZn/0Ii61B2z3VFUTe0yjrKCBrhvg8A=','UserProfile268.jpeg','','TWpiVrNyZaM0DiyHUdJmaw==','Lychee');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (26,'','2022-07-20 11:49:32.416000000','jdmccork@gmail.com','Kenny','Sodgers','','VZtZCkaxpi3GUcz6YzwvxYFh4YaU15M0hCCLrS8TOoc=',null,'','T1Ng4/jSO+QJrWTSDYkuUA==','kenzo');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (27,'','2022-07-20 13:35:25.301000000','Steve.mc@gmail.com','Steve','Mcdonald','Stevo','uk/28T87euD0HDi6Qhc2u+LQBrQvn0RlG4RQr1COx7Y=',null,'','nmzB8SivVi4oqd3+FfM2KA==','steve');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (28,'','2022-07-21 08:17:00.966000000','Gabe123@gmail.com','Gabrial','Newman','Gabby','WKvEW+sfSrLnSKNL85PI5wlItRKm5YxPkIZnkvgImy4=',null,'','HILp2OwKr+fzcKwk0tLaDg==','Gabe');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (29,'','2022-07-21 08:18:22.572000000','orian@canterbury.ac.nz','Orion','Horwatt','','H/Vqpr+vL0/0ccS3abKQ5zKhO71q4z9Cmhh3oFuP5o0=',null,'','QH1Eb0MmqV897f/QrY0MYg==','Orian');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (30,'Magpies are pretty neat','2022-07-21 08:19:33.965000000','jcl2000@canterbury.ac.nz','Jamie','Cordwell','','BG0BqiI9HTaL5mL5uSVbjx55oaX7BAKF6J/QsftB2CI=',null,'','GSFq9ohlhY4r09rjl3+RHQ==','Jamie');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (31,'','2022-07-21 08:20:25.83000000','lilly@gmail.com','Lilly','Walker','','xNscrseiuZG32T8DhYRh945tcWAfPry5+CWcxDVRqdE=',null,'','f6RQVYipSk6Bb9RNijoACA==','Lilly');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (32,'','2022-07-21 08:21:36.359000000','thinMouse@gmail.com','Johannes','Buttner','','T+R6qzp4YP4qNFfx2TntK6vxZe0hFNRAtgixIrRMsUg=',null,'','2q1DlFVKKVD9rhnUe3ukgQ==','ThinMouse');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (33,'','2022-07-21 08:29:03.74000000','Emmey@gmail.com','Emily','Charles','','fuWcUoKvPxkOvPEZYcLV2HGRPmA4x6X6npmKeGH0a2g=',null,'','QMkDB5M+vwU/PbvzAXrJhw==','exor');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (34,'','2022-07-21 08:30:03.764000000','mkp281@canterbury.ac.nz','Mark','Plier','','3U/9Xl8oayj4QuNYgcs/+cJsIH15cbG/iBmSppUwwqY=',null,'','efu3CCvm9R3uBmWkoRw8dg==','Mark');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (35,'','2022-07-21 08:31:10.424000000','oreo@gmail.com','Emily','Sin','','MCu65m9w9eEV3OfOiW12C4gLJf719Xqk0hltuE9v23s=',null,'','tdtZdKPWK8ff/zvw7MO3CQ==','oreos');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (36,'','2022-07-21 08:32:03.181000000','grannyEv@gmail.com','Evelyn','Mullner','','4ZyqEAPWDAki9ygk2XmI825C5PRjCouUwfh/m6YIVRc=',null,'','qjt4qJJ2PyLHqwyrS596HQ==','Granny');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (37,'','2022-07-21 08:33:26.31000000','kuj195@canterbury.ac.nz','Keitaro','Ujiie','','mjC2Jt9Vx6Sj4F5811q6YU5zjxwragir9k+cGCfOae8=',null,'','foZnz8JqurmsRbiUdfOXsw==','Snail');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (38,'','2022-07-21 08:34:59.367000000','joesy@gmail.com','Joe','Cantor','Guitar','+qMgqH07ppaBZCkM3yZhET2mLaBhut2CR2Ryb47swQo=',null,'','w1EwY7p96WOTiyyzKm59TQ==','Tally');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (39,'','2022-07-21 08:36:37.427000000','imCarly@hotmail.com','Carly','Frank','','Axtu9JOuWHFNufVKm2omRNE4ueiy/tdo1U94nnvuwoI=',null,'','/SGsQIVJ7qZEWEi1jPfsfA==','Ghost');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (40,'','2022-07-21 08:38:24.924000000','ERozman@gmail.com','Eric','Rozman','','WKr6T8pGRxmJTXQxt2rkE6E/IJn9p3e2sAaWMPqYfu8=',null,'','KYuXtlPVeUr1A5eMTgdgww==','Kalahari');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (41,'','2022-07-21 08:39:41.112000000','MaggiePie@gmail.com','Maggie','Heath','','jolRfkq/PfhJ924kfAUppiXcXPdViCiHmpOKGNmlVRU=',null,'','+BvsOoKa+86Sn4sNF9ehpA==','Wormwood');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (42,'','2022-07-21 08:41:41.752000000','LRosen@gmail.com','Levy','Rosen','','8goHvLusvJiIj/uDB1pVxK+bO8xZNJ3T/TjdADRNY8M=',null,'','v9nSlrzuP7W5CEz7iJb/fA==','Racoon');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (43,'','2022-07-21 08:43:51.494000000','raymond@gmail.com','Ray','Mcdonald','Raymond','brWo88AV+eI3c8qbOHW2eZsA6hZPSZsMLorlmK0tiGQ=',null,'','R7LRM+soTePK3jJ2CRWBEw==','EXYLD');
MERGE INTO user (user_id, bio,date_created,email,first_name,last_name,nickname,password,profile_image_path,pronouns,salt,username) VALUES (44,'','2022-07-21 08:45:16.945000000','mario.russo@xtra.co.nz','Mario','Russo','','v86TaJPuaDW8Td0F4JYX51coW62/8CKU5ciLA4+DzdQ=',null,'','AyXr+VxVEMtEAYI+eyiHtQ==','Mario');

MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (1,1,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (2,1,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (2,1,1);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (3,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (3,1,1);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (3,2,2);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (4,2,1);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (4,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (5,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (6,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (7,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (8,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (9,2,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (10,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (11,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (12,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (13,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (14,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (15,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (16,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (17,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (18,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (19,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (20,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (21,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (22,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (23,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (24,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (25,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (26,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (27,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (28,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (29,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (30,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (31,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (32,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (33,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (34,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (35,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (36,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (37,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (38,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (39,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (40,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (41,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (42,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (43,0,0);
MERGE INTO user_roles (user_user_id,roles,order_column) VALUES (44,0,0);

MERGE INTO groups (group_id,short_name,long_name) VALUES (1, 'Team 400', '400: Bad Request');
MERGE INTO groups (group_id,short_name,long_name) VALUES (2, 'Team 300', 'Bolt Development');

MERGE INTO users_groups (user_id, group_id) KEY(user_id, group_id) VALUES (1, 1);
MERGE INTO users_groups (user_id, group_id) KEY(user_id, group_id) VALUES (1, 2);
MERGE INTO users_groups (user_id, group_id) KEY(user_id, group_id) VALUES (2, 1);
MERGE INTO users_groups (user_id, group_id) KEY(user_id, group_id) VALUES (4, 1);
MERGE INTO users_groups (user_id, group_id) KEY(user_id, group_id) VALUES (16, 2);
